using UnityEngine;
using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace FishSortLocal {
 public sealed class FixtureRandom:IUnitRandom {public double value;public FixtureRandom(double v){value=v;}public double Next(){return value;}}
 public sealed class FixtureCountry:ICountryProvider {readonly string value;public FixtureCountry(string v){value=v;}public string GetCountry(){return value;}}
 public sealed class RepeatCallbackProvider:IAdProvider {public Action<AdOutcome> callback;public void Show(AdRequest r,Action<AdOutcome> cb){callback=cb;}public void Cancel(){}}
 [Serializable] public class NumericOracle {public NumericRow[] rows;public WalletRow[] wallets;}
 [Serializable] public class NumericRow {public double value,@fixed,floor;}
 [Serializable] public class WalletRow {public double top,piggy,raw,topAdd,piggyAdd,topAfter,piggyAfter;}
 public sealed partial class FishSortGame {
  IEnumerator BusinessCheck(){
   var notes=new List<string>();Action<bool,string> check=(ok,message)=>{if(!ok){File.WriteAllLines(Path.Combine(testDir,"business-tests.txt"),notes.Concat(new[]{"FAIL "+message}));Debug.LogError("BUSINESS_TEST_FAIL "+message);Application.Quit(1);throw new Exception(message);}notes.Add("PASS "+message);};
   Action<double,double,string> equal=(a,b,msg)=>check(Math.Abs(a-b)<1e-10,msg+" expected="+b.ToString("R")+" actual="+a.ToString("R"));
   yield return null;
   var oracle=JsonUtility.FromJson<NumericOracle>(Resources.Load<TextAsset>("numeric-oracle").text);
   foreach(var row in oracle.rows){equal(SourceEconomy.FixedTwo(row.value),row.@fixed,"JS toFixed "+row.value);equal(SourceEconomy.FloorTwo(row.value),row.floor,"JS floorTwo "+row.value);}
   foreach(var row in oracle.wallets){var state=new EconomyState{top=row.top,piggy=row.piggy};var e=new SourceEconomy(state,new FixtureRandom(0),countryProvider,configProvider);var r=e.Credit("oracle","v2_pass",row.raw);equal(r.topAdd,row.topAdd,"wallet main share "+row.raw);equal(r.piggyAdd,row.piggyAdd,"wallet piggy share "+row.raw);equal(state.top,row.topAfter,"wallet main accumulated "+row.raw);equal(state.piggy,row.piggyAfter,"wallet piggy accumulated "+row.raw);}
   var rng=new FixtureRandom(0);var st=new EconomyState();var model=new SourceEconomy(st,rng,countryProvider,configProvider);
   var defaults=RuleConfig.Default();check(defaults.mc.Length==14&&defaults.pac.Length==3,"14 money rows and 3 cadence rows");
   foreach(var rule in defaults.mc){double wallet=rule.end==-1?301:(rule.start+rule.end)/2;rng.value=0;equal(model.BaseReward(wallet),SourceEconomy.FixedTwo(rule.min),"inclusive minimum wallet="+wallet);rng.value=.9999999999;equal(model.BaseReward(wallet),SourceEconomy.FixedTwo(rule.max),"inclusive maximum wallet="+wallet);}
   foreach(var row in new[]{new[]{40.0,2.0},new[]{40.001,1.0},new[]{100.0,.01},new[]{100.001,4.0},new[]{300.0,.05},new[]{300.001,1.0}}){rng.value=0;equal(model.BaseReward(row[0]),row[1],"first-match boundary "+row[0]);}
   equal(SourceEconomy.RandomInteger(0,1000,1002),1000,"random lower endpoint");equal(SourceEconomy.RandomInteger(.999999,1000,1002),1002,"random upper endpoint");
   var sample=new SourceEconomy(new EconomyState(),new SeededUnitRandom(12345),countryProvider,configProvider);var sample2=new SourceEconomy(new EconomyState(),new SeededUnitRandom(12345),countryProvider,configProvider);bool deterministic=true,inRange=true;double lo=100,hi=0;for(int i=0;i<10000;i++){double a=sample.BaseReward(75),b=sample2.BaseReward(75);deterministic&=a==b;inRange&=a>=.2&&a<=.4;lo=Math.Min(lo,a);hi=Math.Max(hi,a);}check(deterministic&&inRange&&lo==.2&&hi==.4,"10,000 seeded draws reproducible, in range, both rounded endpoints reached");
   st.passNum=2;equal(model.AwardAmount("v2_pass",.2),26.72,"first completion special reward");st.passNum=3;equal(model.AwardAmount("v2_pass",.2),38.64,"second completion special reward");st.passNum=4;equal(model.AwardAmount("v2_pass",.2),42.32,"third completion special reward");st.passNum=5;equal(model.AwardAmount("v2_pass",.2),.2,"later completion preset");equal(model.AwardAmount("v2_novice"),50,"new-player gift default");st.top=730;equal(model.AwardAmount("v2_limitTask"),50,"time-limit <=730");st.top=730.001;rng.value=0;equal(model.AwardAmount("v2_limitTask"),1,"time-limit >730 fallback table");
   var split=model.Credit("idempotent","v2_spinReward",20,2);double storedTop=st.top;check(split.raw==20&&split.rate==2&&st.top==storedTop,"native record stores raw amount and rate separately");check(model.Credit("idempotent","v2_spinReward",20,2)==null&&st.top==storedTop,"persistent receipt deduplicates duplicate reward");check(model.Credit("skip","v2_pass",50,1,1)==null&&st.top==storedTop,"flag1 skips every credit mutation");
   foreach(string country in new[]{"us","br","id","ru","kr","jp","de","in","unknown"}){var countryState=new EconomyState();var ce=new SourceEconomy(countryState,new FixtureRandom(0),new FixtureCountry(country),configProvider);var cr=ce.Credit("country","v2_fly",2);check(cr.raw==2&&countryState.top==1.8&&countryState.piggy==.2,"country "+country+" changes display only");}
   check(countryProvider.GetCountry()=="us"&&st.country=="us","replaceable country provider defaults to us");check(SourceEconomy.Display(1,"us")=="1.00"&&SourceEconomy.Display(1.2,"us")=="1.2","US source integer/fraction display rule");check(SourceEconomy.Display(123.45,"id")=="1.234.500"&&SourceEconomy.Display(12.34,"in")=="1,234","source grouping and display multipliers");
   var incoming=new RuleConfig{mc=new[]{new MoneyRule(0,-1,7,7)},pac=new[]{new ForceRule(1,-1,7)},provenance="local fixture override"};check(model.OverrideConfig(incoming),"valid local mc/pac override accepted");equal(model.BaseReward(500),7,"override replaces default reward table");check(model.ForceVideo(7),"override replaces cadence");check(!model.OverrideConfig(new RuleConfig{mc=new[]{new MoneyRule(0,-1,10,1)},pac=incoming.pac}),"invalid override rejected atomically");equal(model.BaseReward(0),7,"invalid override preserves accepted table");
   check(model.ApplyConfigFields(new[]{new MoneyRule(0,-1,9,9)},null,"mc-only fixture"),"partial mc override keeps pac");equal(model.BaseReward(300),9,"mc-only override applied");check(model.ForceVideo(7),"mc-only preserves previous pac");check(model.ApplyConfigFields(null,new[]{new ForceRule(1,-1,4)},"pac-only fixture"),"partial pac override keeps mc");equal(model.BaseReward(0),9,"pac-only preserves mc");check(model.ForceVideo(4),"pac-only changes cadence");model.OverrideConfig(incoming);
   check(SourceEconomy.NormalizeCountry("BR")=="br"&&SourceEconomy.NormalizeCountry("unrecognized")=="us","country normalization and unsupported fallback");foreach(var c in new[]{"us","br","id","ru","kr","jp","de","in"})check(art.ContainsKey(SourceEconomy.MoneyAsset(c,false))&&art.ContainsKey(SourceEconomy.MoneyAsset(c,true)),"country small/large assets loaded "+c);
   var taskPlaceholder=new TimeLimitTaskPlaceholder();NativeRewardOutcome taskOutcome=NativeRewardOutcome.Success;taskPlaceholder.Show(1,"2",o=>taskOutcome=o);check(taskOutcome==NativeRewardOutcome.Unavailable,"native task placeholder does not fabricate eligibility");
   st.onlineDay="01/01";st.onlineRemaining=30;st.onlineReward=0;st.onlineIndex=0;model.UpdateOnline(29.9,"01/01");check(st.onlineRemaining>0&&model.ClaimOnline("early")==null,"online cannot claim before foreground interval");model.UpdateOnline(.2,"01/01");equal(st.onlineReward,10.5,"online stored amount 1.5 times sampled base");model.OverrideConfig(RuleConfig.Default());model.UpdateOnline(50,"01/01");equal(st.onlineReward,10.5,"ready online value persists across time/config changes");var online=model.ClaimOnline("online");check(online!=null&&st.onlineIndex==1&&st.onlineRemaining==60,"first online claim advances interval to60");check(model.ClaimOnline("online-again")==null,"online cannot claim twice immediately");model.UpdateOnline(60,"01/01");model.ClaimOnline("online2");check(st.onlineIndex==2&&st.onlineRemaining==120,"second claim advances to120");for(int i=0;i<8;i++){model.UpdateOnline(120,"01/01");model.ClaimOnline("loop"+i);}check(st.onlineIndex==6&&st.onlineRemaining==120,"online queue index clamps6");model.UpdateOnline(0,"01/02");check(st.onlineIndex==0&&st.onlineRemaining==30&&st.onlineReward==0,"new local day resets online state");
   st.spinUses=0;st.spinProgress=0;check(model.SpinTarget==2&&!model.SpinReady,"first spin requires2 progress");model.AdvancePass();check(!model.SpinReady,"one progress remains locked");model.AdvancePass();check(model.SpinReady,"two progress unlocks first spin");st.spinUses=1;st.spinProgress=0;check(model.SpinTarget==3&&!model.SpinReady,"subsequent spin target3");for(int i=0;i<5;i++)model.AdvancePass();check(st.spinProgress==3&&model.SpinReady,"progress clamps current target");var counts=new int[8];for(int i=0;i<1000;i++)counts[SourceEconomy.SpinIndex(i)]++;check(counts.SequenceEqual(new[]{1,300,0,200,100,0,299,100}),"enumerate all 1,000 spin draw outcomes with inclusive boundaries");check(SourceEconomy.SpinMultipliers.SequenceEqual(new[]{10,1,5,2,3,7,1,2}),"source spin8 multipliers");
   foreach(var cadence in new[]{new[]{5,1},new[]{50,1},new[]{51,0},new[]{54,1},new[]{100,0},new[]{101,0},new[]{103,1}})check(model.ForceVideo(cadence[0])==(cadence[1]==1),"forced cadence boundary "+cadence[0]);
   string serialized=JsonUtility.ToJson(st);var reloadState=JsonUtility.FromJson<EconomyState>(serialized);var reloaded=new SourceEconomy(reloadState,new FixtureRandom(0),countryProvider,configProvider);check(reloadState.top==st.top&&reloadState.piggy==st.piggy&&reloadState.spinUses==st.spinUses&&reloadState.onlineRemaining==st.onlineRemaining&&reloadState.receipts.SequenceEqual(st.receipts),"JSON roundtrip wallets, progress, countdown and receipts");check(reloaded.Credit("idempotent","v2_spinReward",20)==null,"dedup survives persistence");
   foreach(var action in new[]{"undo","add","skip","spin","bonus","forceClose","passDouble","fly"}){var r=SourceAdCoordinator.Route(action);check(r.kind==(action=="forceClose"?AdKind.Interstitial:AdKind.Rewarded),"ad type "+action);foreach(var outcome in new[]{AdOutcome.EligibleClosed,AdOutcome.Failed,AdOutcome.Cancelled}){var malicious=new RepeatCallbackProvider();var gate=new SourceAdCoordinator(malicious);int calls=0;bool awarded=false;check(gate.Begin(r,0,2,(o,q)=>{calls++;awarded=o==AdOutcome.EligibleClosed;}),"ad begins "+action+" "+outcome);check(!gate.Begin(r,1,2,(o,q)=>{}),"pending reentry blocked "+action+" "+outcome);malicious.callback(outcome);malicious.callback(AdOutcome.EligibleClosed);check(calls==1&&awarded==(outcome==AdOutcome.EligibleClosed),"outcome + duplicate callback "+action+" "+outcome);check(!gate.Begin(r,1,2,(o,q)=>{}),"debounce survives outcome "+action+" "+outcome);check(gate.Begin(r,2,2,(o,q)=>calls++),"debounce endpoint reentry "+action+" "+outcome);var stale=malicious.callback;gate.Cancel();stale(AdOutcome.EligibleClosed);check(calls==1,"cancel invalidates stale callback "+action+" "+outcome);}}
   check(SourceAdCoordinator.Route("add").toolTag=="1"&&SourceAdCoordinator.Route("undo").toolTag=="2"&&SourceAdCoordinator.Route("skip").toolTag=="3"&&SourceAdCoordinator.Route("spin").nativePlacement=="30"&&SourceAdCoordinator.Route("bonus").nativePlacement=="0"&&SourceAdCoordinator.Route("fly").nativePlacement=="10","native ad routing tags");var sdk=new SdkAdProviderPlaceholder();AdOutcome placeholder=AdOutcome.EligibleClosed;sdk.Show(SourceAdCoordinator.Route("spin"),o=>placeholder=o);check(placeholder==AdOutcome.Unavailable,"empty SDK placeholder never invents a reward");
   // Production methods, not only numerical helpers.
   check(bakedClips.Count==51&&bakedClips.Keys.Count(k=>!k.StartsWith("online_"))==35&&bakedClips.Keys.Where(k=>!k.StartsWith("online_")||k.StartsWith("online_us_")).All(k=>animationTextures.ContainsKey(k)&&animationTextures[k]!=null),"35 original clips preserved;16 country clips indexed;default US source clips loaded");bool cries=true;for(int i=0;i<10;i++){PlayFishCry(i);cries&=lastSoundRequested=="BirdTweet"+(Math.Min(i,8)+1)&&Resources.Load<AudioClip>("Audio/audio_"+lastSoundRequested)!=null;}check(cries,"10 fish identities use actual source audio clips");
   LoadLevel(8);LayoutBranches();check(Board.Stands.Select((b,i)=>b.side==(i%2==0?-1:1)).All(x=>x)&&Math.Abs(branchRects[0].y-branchRects[1].y)<.001,"source alternating branches and even layout preserved");Board.AddStand();LayoutBranches();check(Math.Abs(branchRects[1].y-branchRects[0].y-130*NativeToDesign)<.001,"source odd layout preserved");
   holdEarlyAutoAdvance=false;LoadLevel(1);TapStand(0);TapStand(1);yield return WaitForBoardMotion();check(Data.level==2&&Data.economy.ledger.Last().raw==26.72,"real move completion advances level and exact early reward");check(Board.ConservedHistogram().Sum()>0&&Board.History.Count==0,"new level has stable fish and fresh history");
   holdEarlyAutoAdvance=true;LoadLevel(1);string beforeUndo=Board.Key();var beforeHistogram=Board.ConservedHistogram();TapStand(0);TapStand(1);yield return WaitForBoardMotion();check(Board.Won&&Board.ClearedFish.Sum()==4,"settled completed group clears all fish with conserved ledger");Data.undo=2;Undo();check(motionInProgress,"undo starts source-duration return motion");yield return WaitForBoardMotion();check(!Board.Won&&Board.Key()==beforeUndo&&Board.ConservedHistogram().SequenceEqual(beforeHistogram)&&Data.undo==1,"animated cleared-group undo restores conserved snapshot and uses one undo");holdEarlyAutoAdvance=false;
   LoadLevel(8);double productionTop=Data.economy.top;int stands=Board.Stands.Count;RequestReward("add");adSimulator.Complete(AdOutcome.Failed);check(Board.Stands.Count==stands&&Data.economy.top==productionTop,"add failure grants neither branch nor money");yield return new WaitForSecondsRealtime(2.05f);RequestReward("add");adSimulator.Complete(AdOutcome.EligibleClosed);check(Board.Stands.Count==stands+1&&Data.economy.addUsedLevel==8,"source add success adds one branch directly");RequestReward("add");check(adCoordinator.Pending==null&&Board.Stands.Count==stands+1,"second add same level ineligible");
   Data.undo=0;RequestReward("undo");adSimulator.Complete(AdOutcome.EligibleClosed);check(Data.undo==3&&Data.economy.top==productionTop,"undo ad success refills3 without cash");yield return new WaitForSecondsRealtime(2.05f);RequestReward("undo");CloseModal();adSimulator.Complete(AdOutcome.EligibleClosed);check(Data.undo==3,"closed request cannot later refill tools");
   int beforeSkip=Data.level;RequestReward("skip");adSimulator.Complete(AdOutcome.EligibleClosed);check(Data.level==beforeSkip+1&&Data.economy.top==productionTop,"skip success advances immediately without currency");
   Data.economy.spinProgress=economy.SpinTarget;Data.economy.firstSpinUsed=false;RequestReward("spin");check(modal=="spinplaying"&&adCoordinator.Pending==null&&Data.economy.spinUses==1,"first eligible spin starts free");CloseModal();check(modal=="spinplaying","source spin blocks close while rotating");yield return new WaitForSecondsRealtime(PendingRewardDuration+.2f);check(modal=="rewardtoast"&&Data.economy.ledger.Last().biz=="v2_spinReward","full9.5-second source spin awards captured amount");ContinueReward();Data.economy.spinProgress=economy.SpinTarget;RequestReward("spin");check(adCoordinator.Pending!=null&&modal=="ad","later eligible spin requires ad");int spinUses=Data.economy.spinUses;adSimulator.Complete(AdOutcome.Cancelled);check(Data.economy.spinUses==spinUses,"cancelled spin ad does not consume progress");
   Data.economy.onlineRemaining=0;Data.economy.onlineReward=1.5;RequestReward("online");check(adCoordinator.Pending==null&&Data.economy.ledger.Last().biz=="v2_onlineReard","online grants without advertisement");
   int ledgerCount=Data.economy.ledger.Count;ClaimNewGift();ClaimNewGift();check(Data.economy.ledger.Count==ledgerCount+1&&Data.economy.ledger.Last().raw==50,"production newbie gift once, no ad");
   applicationFocused=false;double remaining=Data.economy.onlineRemaining;yield return new WaitForSecondsRealtime(.3f);check(Data.economy.onlineRemaining==remaining,"background online countdown pauses");applicationFocused=true;
   Save();var disk=JsonUtility.FromJson<SaveData>(File.ReadAllText(savePath));check(disk.economy.top==Data.economy.top&&disk.economy.piggy==Data.economy.piggy&&disk.economy.country=="us","production save persists separate wallets and US profile");
   LoadLevel(4);Board=new PuzzleModel(new BoardSnapshot{stands=new List<Stand>{new Stand{side=-1},new Stand{side=1}}});CompleteSourceLevel();double beforeNormal=Data.economy.top;RequestReward("passDouble");var normalRequest=adCoordinator.Pending;check(normalRequest!=null&&normalRequest.amount==2*completedBase&&Data.level==4,"normal doubled reward captures amount and waits for ad");adSimulator.Complete(AdOutcome.Failed);check(Data.level==4&&Data.economy.top==beforeNormal,"normal failure stays on completed level without payout");ClaimCompleted(false);check(Data.level==5&&Data.economy.ledger.Last().biz=="v2_pass","normal base close credits and advances without ad");
   LoadLevel(5);Board=new PuzzleModel(new BoardSnapshot{stands=new List<Stand>{new Stand{side=-1},new Stand{side=1}}});CompleteSourceLevel();check(completedForce,"forced route uses recovered level5 cadence");double beforeForce=Data.economy.top;ClaimCompleted(false);var forcedRequest=adCoordinator.Pending;check(forcedRequest!=null&&forcedRequest.kind==AdKind.Interstitial&&Data.level==6,"forced close non-white fixture opens interstitial and advances immediately");adSimulator.Complete(AdOutcome.Cancelled);check(Data.level==6&&Data.economy.top==beforeForce,"forced cancellation preserves advancement but awards nothing");
   LoadLevel(10);Board=new PuzzleModel(new BoardSnapshot{stands=new List<Stand>{new Stand{side=-1},new Stand{side=1}}});CompleteSourceLevel();yield return new WaitForSecondsRealtime(3.05f);double capturedBase=completedBase;RequestReward("bonus");check(Data.level==11&&adCoordinator.Pending.amount==2*capturedBase,"forced double captures2x before immediate next level");adSimulator.Complete(AdOutcome.EligibleClosed);check(Data.economy.ledger.Last().raw==2*capturedBase&&Data.economy.ledger.Last().rate==2&&Data.economy.ledger.Last().biz=="v2_passd","forced double credits captured raw value with rate metadata");
   LoadLevel(15);Board=new PuzzleModel(new BoardSnapshot{stands=new List<Stand>{new Stand{side=-1},new Stand{side=1}}});CompleteSourceLevel();localWhiteBao=true;ClaimCompleted(false);check(Data.level==16&&adCoordinator.Pending==null&&Data.economy.ledger.Last().biz=="v2_passd","explicit white-mode fixture bypasses interstitial");localWhiteBao=false;
   LoadLevel(8);RequestReward("fly");double beforeFly=Data.economy.top;adSimulator.Complete(AdOutcome.Failed);check(Data.economy.top==beforeFly,"fly ad failure no payout");yield return new WaitForSecondsRealtime(2.05f);RequestReward("fly");adSimulator.Complete(AdOutcome.EligibleClosed);check(Data.economy.ledger.Last().biz=="v2_fly"&&flyStartedAt<0&&nextFlyAt-Time.unscaledTime>=14.9f,"fly success samples reward and schedules next15..20-second entry");
   LoadLevel(8);RequestReward("undo");int oldUndo=Data.undo;var oldSimulator=adSimulator;LoadLevel(9);oldSimulator.Complete(AdOutcome.EligibleClosed);check(Data.undo==oldUndo&&Data.level==9,"level replacement invalidates pending ad reward");
   yield return RevisionBusinessCheck(check,equal);
   LoadLevel(8);modal="";yield return Capture("business-main-us");Open("business");yield return Capture("business-review-us");Open("piggy");yield return Capture("business-piggy-us");Open("spin");yield return Capture("business-spin-us");
   File.WriteAllLines(Path.Combine(testDir,"business-tests.txt"),notes);File.WriteAllText(Path.Combine(testDir,"business-state.json"),JsonUtility.ToJson(Data,true));Debug.Log("BUSINESS_TESTS_PASS "+notes.Count);Application.Quit(0);
  }
 }
}
