using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace FishSortLocal {
 public sealed class ImmediateAdFixture:IAdProvider {public int shows,cancels;public AdOutcome outcome=AdOutcome.EligibleClosed;public bool throws;public void Show(AdRequest request,Action<AdOutcome> done){shows++;if(throws)throw new Exception("fixture show failure");done(outcome);done(AdOutcome.EligibleClosed);}public void Cancel(){cancels++;}}
 public sealed class TaskRoutingFixture:ITimeLimitTaskProvider {public int type,calls;public string value;public Action<NativeRewardOutcome> callback;public void Show(int t,string v,Action<NativeRewardOutcome> done){calls++;type=t;value=v;callback=done;}}
 [Serializable] public sealed class RevisionScenarioReport {public string[] independent_scenarios;public int independent_scenario_count;public string scope;}
 public sealed partial class FishSortGame {
  void ResetRevisionFixture(int level){CancelPendingReward();adProviderOverride=null;Data=new SaveData{economy=new EconomyState{top=100}};Board=null;InitBusiness();LoadLevel(level);applicationFocused=true;nextOnlineClick=nextTaskClick=0;taskProvider=new TimeLimitTaskPlaceholder();}
  void CompleteConservedFixture(){var won=Board.Snapshot();won.clearedFish=Board.ConservedHistogram();foreach(var stand in won.stands)stand.fish.Clear();Board=new PuzzleModel(won);CompleteSourceLevel();}
  IEnumerator RevisionBusinessCheck(Action<bool,string> check,Action<double,double,string> equal){
   var scenarios=new List<string>();
   scenarios.Add("Synchronous eligible spin callback completes one captured transaction");
   ResetRevisionFixture(8);Data.economy.firstSpinUsed=true;Data.economy.spinUses=2;Data.economy.spinProgress=economy.SpinTarget;var immediate=new ImmediateAdFixture();SetAdProvider(immediate);RequestReward("spin");string receipt=Data.economy.pendingSpin.receipt;double amount=Data.economy.pendingSpin.amount;
   check(modal=="spinplaying"&&rewardPending&&adCoordinator.Pending==null&&Data.economy.spinUses==3,"sync production provider leaves spinplaying, never overwritten with ad");check(ActiveAdSimulator==null,"external provider has no simulator reward controls");yield return new WaitForSecondsRealtime(9.7f);check(modal=="rewardtoast"&&Data.economy.pendingSpin==null&&Data.economy.ledger.Count(x=>x.id==receipt)==1,"sync duplicate callbacks + full spin credit exactly once");equal(Data.economy.ledger.Last().raw,amount,"sync spin captured raw amount");FinishSourceSpin();check(Data.economy.ledger.Count==1,"repeated spin finish cannot credit twice");
   scenarios.Add("Synchronous normal doubled reward advances once and preserves callback UI");
   ResetRevisionFixture(4);CompleteConservedFixture();double basis=completedBase;SetAdProvider(new ImmediateAdFixture());ClaimCompleted(true);check(Data.level==5&&modal=="rewardtoast"&&Data.economy.pendingLevel==null,"sync normal reward callback advances and keeps reward toast");equal(Data.economy.ledger.Last().raw,2*basis,"sync normal double captured amount");check(Data.economy.ledger.Count==1,"sync normal duplicate provider completion pays once");
   scenarios.Add("Forced victory opens pointer panel and synchronous callback runs after advance");
   ResetRevisionFixture(5);CompleteConservedFixture();check(modal=="bonus"&&completedForce&&HasCompletedReward,"normal forced victory enters actual pointer/chest panel");basis=completedBase;SetAdProvider(new ImmediateAdFixture());ClaimBonus(3);check(Data.level==6&&modal=="rewardtoast"&&Data.economy.ledger.Count==1,"sync forced callback sees already advanced board, toast remains");equal(Data.economy.ledger.Last().raw,2*basis,"source forced video button fixed2x despite decorative pointer3x");
   scenarios.Add("External async provider uses cancel-only UI and discards late callbacks");
   ResetRevisionFixture(8);var delayed=new RepeatCallbackProvider();SetAdProvider(delayed);int undo=Data.undo;RequestReward("undo");check(modal=="ad"&&adCoordinator.Pending!=null&&ActiveAdSimulator==null,"async external provider modal has no local simulator");yield return Capture("revision-external-provider-pending");var late=delayed.callback;CancelActiveAd();late(AdOutcome.EligibleClosed);check(Data.undo==undo&&adCoordinator.Pending==null&&modal=="","external cancel invalidates late provider reward");
   scenarios.Add("Provider replacement cancels pending request and selects injected simulator");
   ResetRevisionFixture(8);delayed=new RepeatCallbackProvider();SetAdProvider(delayed);RequestReward("add");late=delayed.callback;var simulator=new LocalAdSimulator();SetAdProvider(simulator);late(AdOutcome.EligibleClosed);check(modal==""&&Data.economy.addUsedLevel==-1,"provider replacement closes pending UI without awarding old request");
   check(adCoordinator.Pending==null&&ActiveAdSimulator==simulator&&Data.economy.addUsedLevel==-1,"provider replacement clears modal and uses injected simulator controls");RequestReward("add");simulator.Complete(AdOutcome.EligibleClosed);check(Data.economy.addUsedLevel==8,"injected local simulator routes its own completion");
   scenarios.Add("SDK unavailable and throwing provider cannot grant cash or leave stuck modal");
   ResetRevisionFixture(8);SetAdProvider(new SdkAdProviderPlaceholder());RequestReward("fly");check(modal==""&&adCoordinator.Pending==null&&Data.economy.ledger.Count==0,"sync unavailable placeholder no cash and no stale ad modal");SetAdProvider(new ImmediateAdFixture{throws=true});RequestReward("fly");check(modal==""&&adCoordinator.Pending==null&&Data.economy.ledger.Count==0,"throwing provider fails safely without payout");
   scenarios.Add("Undo refill eligibility precedes empty-history check");
   ResetRevisionFixture(8);Data.undo=0;Undo();check(Board.History.Count==0&&adCoordinator.Pending!=null,"empty history + zero undo opens source refill ad");adSimulator.Complete(AdOutcome.EligibleClosed);check(Data.undo==3&&Data.economy.ledger.Count==0,"empty-history refill grants3 uses without cash");
   scenarios.Add("Restart resets branch-add qualification");
   ResetRevisionFixture(8);int branches=Board.Stands.Count;RequestReward("add");adSimulator.Complete(AdOutcome.EligibleClosed);LoadLevel(8);check(Data.economy.addUsedLevel==-1&&Board.Stands.Count==branches,"same-level restart resets added branch and qualification");yield return new WaitForSecondsRealtime(2.05f);RequestReward("add");adSimulator.Complete(AdOutcome.EligibleClosed);check(Board.Stands.Count==branches+1&&Data.economy.addUsedLevel==8,"same-level restart permits one new successful added branch");
   scenarios.Add("350+ actual levels reuse150..348 source boards without clamping progress");
   ResetRevisionFixture(350);RequestReward("skip");adSimulator.Complete(AdOutcome.EligibleClosed);check(Data.level==351&&Data.economy.passNum==351&&Data.sourceLevel>=150&&Data.sourceLevel<=348,"skip350 reaches351 and preserves real progress");string key=Board.Key();int sourceLevel=Data.sourceLevel;Save();var previousData=Data;LoadSave();check(!ReferenceEquals(previousData,Data),"disk reload actually replaces current save object; no swallowed recovery error");check(Data.level==351&&Data.sourceLevel==sourceLevel&&Board.Key()==key,"350+ chosen resource survives actual save load");bool range=true;for(int i=0;i<200;i++){LoadLevel(351+i);range&=Data.sourceLevel>=150&&Data.sourceLevel<=348&&Data.level==351+i;}check(range,"200 successive high levels use recovered150..348 range");
   scenarios.Add("Task1..4 routing, duplicate, stale and unavailable native callbacks");
   ResetRevisionFixture(8);Data.economy.limitTaskDisBlock=17;Data.economy.limitTaskZhuanpan=9;string[] values={"8","0","17","9"};for(int type=1;type<=4;type++){var task=new TaskRoutingFixture();SetTimeLimitTaskProvider(task);SetTimeLimitTaskType(type);nextTaskClick=0;RequestTimeLimitTask(taskProvider);check(task.type==type&&task.value==values[type-1],"production native task payload type"+type);RequestTimeLimitTask(taskProvider);check(task.calls==1,"native task pending/debounce guard type"+type);int count=Data.economy.ledger.Count;task.callback(NativeRewardOutcome.Success);task.callback(NativeRewardOutcome.Success);check(Data.economy.ledger.Count==count+1,"native task callback once type"+type);}
   var oldTask=new TaskRoutingFixture();SetTimeLimitTaskProvider(oldTask);nextTaskClick=0;RequestTimeLimitTask(taskProvider);int oldCount=Data.economy.ledger.Count;SetTimeLimitTaskProvider(null);oldTask.callback(NativeRewardOutcome.Success);check(Data.economy.ledger.Count==oldCount&&!taskPending,"native provider replacement discards stale callback");nextTaskClick=0;RequestTimeLimitTask(taskProvider);check(Data.economy.ledger.Count==oldCount&&!taskPending,"native task placeholder unavailable never invents eligibility");check(Data.economy.limitTaskDisBlock==17,"unknown disblock counter never fabricated by callback");
   scenarios.Add("Source online one-second guard and focus-loss disk persistence");
   ResetRevisionFixture(8);Data.economy.onlineRemaining=0;Data.economy.onlineReward=1.5;RequestReward("online");int claims=Data.economy.ledger.Count;Data.economy.onlineRemaining=0;Data.economy.onlineReward=2;RequestReward("online");check(Data.economy.ledger.Count==claims,"production online click guard blocks within1second even if ready fixture");yield return new WaitForSecondsRealtime(1.05f);RequestReward("online");check(Data.economy.ledger.Count==claims+1,"online click allowed at source debounce boundary");Data.economy.onlineRemaining=37.25;OnApplicationFocus(false);var disk=JsonUtility.FromJson<SaveData>(File.ReadAllText(savePath));equal(disk.economy.onlineRemaining,37.25,"focus loss persists foreground countdown");yield return new WaitForSecondsRealtime(.2f);equal(Data.economy.onlineRemaining,37.25,"focus-lost countdown paused");OnApplicationFocus(true);
   scenarios.Add("Production ad gate uses each route actual debounce duration");
   foreach(string action in new[]{"undo","add","skip","spin","bonus","forceClose","passDouble","fly"}){var provider=new ImmediateAdFixture();var gate=new SourceAdCoordinator(provider);double debounce=SourceAdCoordinator.Debounce(action);var req=SourceAdCoordinator.Route(action);int callbacks=0;check(gate.Begin(req,100,debounce,(o,r)=>callbacks++),"route-specific begin "+action);check(!gate.Begin(req,100+debounce-.001,debounce,(o,r)=>callbacks++),"route-specific guard before boundary "+action);check(gate.Begin(req,100+debounce,debounce,(o,r)=>callbacks++),"route-specific boundary "+action);check(callbacks==2,"route-specific sync callback once "+action);}
   File.WriteAllText(Path.Combine(testDir,"revision-independent-scenarios.json"),JsonUtility.ToJson(new RevisionScenarioReport{independent_scenarios=scenarios.ToArray(),independent_scenario_count=scenarios.Count,scope="12 named production scenarios; repeated assertions are counted separately. Cross-process recovery is a separate runner."},true));
   ResetRevisionFixture(8);
  }
 }
}
